
title: "your_awesome_title"
email: your-email@example.com
description: >-
  My site jekyll theme
baseurl: "/"
url: ""

# Theme config
clyell:
  disqus: gjuniioor
  nick: "gjuniioor"
  bye_message: "Thx!"
# Build settings
remote_theme: nitanmarcel/clyell

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-tidy
  - jekyll-remote-theme

markdown: kramdown
permalink: /:categories/:title/