
title: "gjuniioor"
email: your-email@example.com
description: >-
  My site jekyll theme
baseurl: "/clyell/"
url: "https://gjuniioor.github.io"

# Theme config

bye_message: "Thx!"
disqus: gjuniioor
nick: "gjuniioor"

# Build settings
theme: clyell

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-tidy

markdown: kramdown
permalink: /:categories/:title/