
title: "gjuniioor"
email: your-email@example.com
description: >-
  My site jekyll theme
baseurl: "/clyell/"
url: "https://gjuniioor.github.io"

# Theme config
clyell:
  disqus: gjuniioor
  nick: "gjuniioor"
  bye_message: "Thx!"
# Build settings
theme: clyell

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-tidy

markdown: kramdown
permalink: /:categories/:title/